export default {
  appName: null,
  anonymousToken: null,
  useAnonymousTokenByDefault: true,
  signUpToken: null,
  apiUrl: 'https://api.backand.com',
  storage: {},
  storagePrefix: 'BACKAND_',
  manageRefreshToken: true,
  runSigninAfterSignup: true,
  runSocket: false,
  socketUrl: 'https://socket.backand.com',
  exportUtils: false,
  isMobile: false,
  mobilePlatform: 'ionic',
};
